### ISSUE TITLE
Question: what hub do I need to make this plugin work?

### ISSUE THREAD

**Issue by CooperCGN** [schemers/homebridge-hunterdouglas-platinum#2]
Is this designed to work with the PowerView hub? What generation?

**Comment by schemers** [comment]
this is designed to work with the older [Platinum Bridge](https://www.hunterdouglas.com/operating-systems/motorized/platinum-technology-app)

It is my understanding that the [PowerView](https://www.hunterdouglas.com/operating-systems/motorized/powerview-motorization/works-with) hub already supports HomeKit, although I don't know which generation since I've got the older Platinum bridge.
